[application]

[web.app]
# HTML title tag content
title = "PlumJam"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]
# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []
