name: "Release"

on:
    push:
        tags:
            - "v*"

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: |
                  bun install tailwindcss @tailwindcss/cli
                  bunx @tailwindcss/cli -i='./input.css' -o='./assets/gen-tailwind.css'
            - uses: moonrepo/setup-rust@v1
              with:
                  inherit-toolchain: true
                  bins: dioxus-cli
                  components: clippy
                  cache-base: master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: cargo clippy
            - run: dx check

    build:
        needs: checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: |
                  bun install tailwindcss @tailwindcss/cli
                  bunx @tailwindcss/cli -i='./input.css' -o='./assets/gen-tailwind.css'
            - uses: moonrepo/setup-rust@v1
              with:
                  inherit-toolchain: true
                  bins: dioxus-cli
                  cache-base: master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Build website
              run: |
                  dx build --release
                  mkdir -p dist
                  cp -r target/dx/plumjam-website/release/web/public/* dist/
                  cp dist/index.html dist/404.html

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: website-build
                  path: dist/

    server-deploy:
        name: Deploy to plum server
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: website-build
                  path: dist/

            - name: List downloaded artifacts
              run: |
                  echo "Downloaded artifacts:"
                  ls -la dist/
                  find dist/ -type f

            - name: Copy build to plum server
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ secrets.PLUM_HOST }}
                  username: ${{ secrets.PLUM_USER }}
                  key: ${{ secrets.PLUM_SSH_KEY }}
                  port: ${{ secrets.PLUM_PORT }}
                  source: "dist/*"
                  target: ${{ secrets.PLUM_TARGET_DIR }}
                  overwrite: true
                  strip_components: 1 # to de-nest dist/* to *

    tagged-release:
        needs: server-deploy
        permissions:
            id-token: write
            contents: write
            packages: write
        runs-on: ubuntu-latest
        steps:
            - uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
